### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by akavkl** [userariii/android-OTA#1]
Again, not an issue, just wanted to know the source's spatial audio and DDP codecs and if you needed to something for those to get working. Thanks in advance

**Comment by userariii** [comment]
I didn't get u

**Comment by userariii** [comment]
Spatial Audio + Dolby codecs are working fine at the same time if u played any supported content.

**Comment by akavkl** [comment]
no not that, I'm trying to make spatial audio as an add-on via the Magisk/KSU module, so for that do you have those commits for adding those?
Sometimes does show up for me in settings but doesn't work and disappears when rebooted, so prolly missing something or did something wrong.

**Comment by userariii** [comment]
[Commit_01](https://github.com/PixelExperience-Devices/device_nokia_sdm660-common/commit/9c4bd2696ef1e0eeaadf0314de0faba0fc874b5b)
[Commit_02](https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_nokia_sdm660-common/-/commit/645fb2bbf075053785575a44f7682a02ece5a301)

Checkout these 2 commits, required to enable Spatial Audio (Note: SpatialAudio supported from A13 build)
